coverage:
  ignore:
    - Tests/ParseSwiftTests/.*
    - TestHost/*
    - TestHostTV/*
  status:
    patch:
      default:
        target: 71
    changes: false
    project:
      default:
        target: 81
comment:
  require_changes: true
