coverage:
  ignore:
    - Tests/ParseSwiftTests/.*
  status:
    patch:
      default:
        target: 55
    changes: false
    project:
      default:
        target: 61
comment:
  require_changes: true
