coverage:
  ignore:
    - Tests/ParseSwiftTests/.*
    - Sources/ParseSwift/Coding/ParseEncoder.swift 
  status:
    patch:
      default:
        target: 49
    changes: false
    project:
      default:
        target: 71
comment:
  require_changes: true
