coverage:
  ignore:
    - Tests/ParseSwiftTests/.*
  status:
    patch:
      default:
        target: 0
    changes: false
    project:
      default:
        target: 80
comment:
  require_changes: true
