coverage:
  ignore:
    - Tests/ParseSwiftTests/.*
    - TestHost/*
    - TestHostTV/*
  status:
    patch:
      default:
        target: 33
    changes: false
    project:
      default:
        target: 89
comment:
  require_changes: true
