coverage:
  ignore:
    - Tests/ParseSwiftTests/.*
    - Sources/ParseSwift/Coding/ParseEncoder.swift 
  status:
    patch:
      default:
        target: 90
    changes: false
    project:
      default:
        target: 80
comment:
  require_changes: true
