coverage:
  ignore:
    - Tests/ParseSwiftTests/.*
  status:
    patch:
      default:
        target: 51
    changes: false
    project:
      default:
        target: 81
comment:
  require_changes: true
