coverage:
  ignore:
    - Tests/ParseSwiftTests/.*
  status:
    patch:
      default:
        target: auto
    changes: false
    project:
      default:
        target: 83
comment:
  require_changes: true
