coverage:
  ignore:
    - Tests/ParseSwiftTests/.*
  status:
    patch:
      default:
        target: 24
    changes: false
    project:
      default:
        target: 74
comment:
  require_changes: true
