version: 1
builder:
  configs:
  - platform: ios
    scheme: "ParseSwift (iOS)"
    documentation_targets: ["ParseSwift"]
  - platform: macos-xcodebuild
    scheme: "ParseSwift (macOS)"
  - platform: macos-xcodebuild-arm
    scheme: "ParseSwift (macOS)"
  - platform: tvos
    scheme: "ParseSwift (tvOS)"
  - platform: watchos
    scheme: "ParseSwift (watchOS)"
