disabled_rules:
  - file_length
  - cyclomatic_complexity
  - function_body_length
  - type_body_length
  - inclusive_language
  - comment_spacing
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Tests/ParseSwiftTests/ParseEncoderTests
  - DerivedData
  - .build
  - .dependencies
