#if !canImport(ObjectiveC)
import XCTest

extension APICommandTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APICommandTests = [
        ("testAPIError", testAPIError),
        ("testErrorServer", testErrorServer),
        ("testExecuteCorrectly", testExecuteCorrectly),
        ("testNotParseErrorType", testNotParseErrorType),
    ]
}

extension AnyCodableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnyCodableTests = [
        ("testJSONDecoding", testJSONDecoding),
        ("testJSONEncoding", testJSONEncoding),
    ]
}

extension AnyDecodableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnyDecodableTests = [
        ("testJSONDecoding", testJSONDecoding),
    ]
}

extension AnyEncodableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnyEncodableTests = [
        ("testJSONEncoding", testJSONEncoding),
    ]
}

extension KeychainStoreTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeychainStoreTests = [
        ("testGetAnyCodableObject", testGetAnyCodableObject),
        ("testGetObject", testGetObject),
        ("testGetObjectBoolTypedSubscript", testGetObjectBoolTypedSubscript),
        ("testGetObjectStringTypedSubscript", testGetObjectStringTypedSubscript),
        ("testGetObjectSubscript", testGetObjectSubscript),
        ("testGetObjectWrongBoolTypedSubscript", testGetObjectWrongBoolTypedSubscript),
        ("testGetObjectWrongStringTypedSubscript", testGetObjectWrongStringTypedSubscript),
        ("testRemoveAllObjects", testRemoveAllObjects),
        ("testRemoveObject", testRemoveObject),
        ("testRemoveObjectSubscript", testRemoveObjectSubscript),
        ("testSetComplextObject", testSetComplextObject),
        ("testSetObject", testSetObject),
        ("testThreadSafeRemoveAllObjects", testThreadSafeRemoveAllObjects),
        ("testThreadSafeRemoveObject", testThreadSafeRemoveObject),
        ("testThreadSafeSet", testThreadSafeSet),
    ]
}

extension ParseObjectCommandTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParseObjectCommandTests = [
        ("testFetch", testFetch),
        ("testFetchCommand", testFetchCommand),
        ("testSave", testSave),
        ("testSaveCommand", testSaveCommand),
        ("testUpdate", testUpdate),
        ("testUpdateCommand", testUpdateCommand),
    ]
}

extension ParseUserCommandTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParseUserCommandTests = [
        ("testFetch", testFetch),
        ("testFetchCommand", testFetchCommand),
        ("testSaveCommand", testSaveCommand),
        ("testUpdate", testUpdate),
        ("testUpdateCommand", testUpdateCommand),
        ("testUserLogin", testUserLogin),
        ("testUserSignUp", testUserSignUp),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(APICommandTests.__allTests__APICommandTests),
        testCase(AnyCodableTests.__allTests__AnyCodableTests),
        testCase(AnyDecodableTests.__allTests__AnyDecodableTests),
        testCase(AnyEncodableTests.__allTests__AnyEncodableTests),
        testCase(KeychainStoreTests.__allTests__KeychainStoreTests),
        testCase(ParseObjectCommandTests.__allTests__ParseObjectCommandTests),
        testCase(ParseUserCommandTests.__allTests__ParseUserCommandTests),
    ]
}
#endif
