bundle exec jazzy \
  --clean \
  --author "Parse Community" \
  --author_url http://parseplatform.org \
  --github_url https://github.com/parse-community/Parse-Swift \
  --root-url http://parseplatform.org/Parse-Swift/api/ \
  --module-version ${BUILD_VERSION} \
  --theme fullwidth \
  --skip-undocumented \
  --output ./docs/api \
  --build-tool-arguments -scheme,'ParseSwift (iOS)',-destination,'name=iPhone 12 Pro Max' \
  --module ParseSwift \
